---

- name: install latest epel-release
  yum:
    name=epel-release
    state=latest

- name: install home:gsfjohnson repo
  copy: src=home:gsfjohnson.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: install pkg
  yum:
    name={{nf_pkg_name}}
    state={{nf_pkg_state}}

- name: copy multi-nfcapd init
  copy:
    src=multi-nfcapd.init
    dest=/etc/init.d/multi-nfcapd
    owner=root
    group=root
    mode=0755
  notify: svc restart nfcapd

- name: multi-nfcapd sysconfig template
  template:
    src=multi-nfcapd.sysconfig.j2
    dest=/etc/sysconfig/multi-nfcapd
    owner=root
    group=root
    mode=0755
  notify: svc restart nfcapd
